### ISSUE TITLE
Разделить utils

### ISSUE THREAD

**Issue by strizh78** [rust379/MApp#118]
перенести в utils

_Originally posted by @strizh78 in https://github.com/rust379/MApp/pull/104#discussion_r720347916_

**Comment by rust379** [comment]
Вынести часть функционала из interface/utils в из interface,

- [ ] Из dosage.cpp вынести combineDosageText как toString

**Comment by strizh78** [comment]
> Вынести часть функционала из interface/utils в из interface

ась?

тут, наверное, есть вопрос как мы хотим это организовать
сделать
utils/utils.*
utils/interfaceUtils.*

или 
utils/utils.*
interface/interfaceUtils.*
?
