### ISSUE TITLE
порядок файлов

### ISSUE THREAD

**Issue by rust379** [rust379/MApp#147]
не лексикографический порядок выглядит не очень

_Originally posted by @rust379 in https://github.com/rust379/MApp/pull/145#discussion_r835642947_

**Comment by strizh78** [comment]
//Метод 1: Импортируйте все профессиональные файлы напрямую, вместо того, чтобы добавлять каждый по одному, что избавляет от беспокойства и усилий.
HEADERS += *.h
SOURCES += *.cpp

//Метод 2: Хранить в папках модулей. Различные модули используют pri для включения файлов кода. Например, интерфейс можно поместить в папку ui, и ниже создается ui.pri, а затем файл проекта pro должен только импортировать его. pri файл.
include($$PWD/ui/ui.pri)
//Вы также можете добавить предложение пути включения, чтобы вам не нужно было писать папку при использовании кода
INCLUDEPATH += $$PWD/ui
//Добавьте указанную выше строку, вы можете напрямую включить «form.h» при использовании файла заголовка, и вам нужно будет включить «ui / form.h», если вы его не добавите.
