### ISSUE TITLE
Шаблоны v1

### ISSUE THREAD

**Issue by rust379** [rust379/MApp#154]
Язык разметки - ручками

1. Шаблоны файлов
2. В услуги подтягиваем шаблоны, которые должны подтягиваться в прием с данной услугой

**Comment by strizh78** [comment]
# Шаблоны
При проведении услуг (например, "приём терапевта 20мин") заполняются какие-то файлы приёма (где могут описываться симптомы/данные пациента/выписанные лекарства и рекомендации). Эти файлы часто аналогичны для разных приёмов по одной услуге (условно каждый "приём терапевта 20 мин" содержит файл "осмотр терапевта" и "согласие на мед вмешательство").

Эти файлы чаще всего имеют некоторые стандартные поля (имя пациента/дату рождения/название услуги/цену/дату приёма/назначенные лекарства и т д), которые мы можем заполнять для пользователя. Для этого делаем шаблонные файлы.

Шаблон это файл, имеющий спец-разметку внутри. Разметка вида добавления файл штук типа  <patient.initials>, в которые в будущем подставляются соответствующие данные.

#### Правила
 - Один шаблон может использоваться несколькими услугами (например, "приём терапевта 20мин" и "приём терапевта 30мин" вероятно будут содержать одинаковый "шаблон осмотра").
 - Одна услуга может иметь несколько шаблонов (например первичный осмотр, справки, согласия).

## Как должно работать с точки зрения пользователя
Надо уметь создавать новые шаблоны, редактировать существующие, добавлять шаблоны к услугам + чтобы они прорастали в приём
### Создание шаблона
Создать шаблон можно из списка шаблонов (который можно открыть через кнопку "Шаблоны" в левом меню) или из форму услуги (там список шаблонов, из которых мы выбираем нужные для этой услуги)

У шаблона есть имя + текст с разметкой (фактически тупо обычный файл, у которого немного необычно парсится текст)

Форма шаблона должна содержать текстовый **редактор**, где пользователь может вписывать общий текст + добавлять разметку, для последующей подстановки туда данных. Также должна быть возможность **предпросмотра** того, что получается (будем подставлять в шаблон некие тестовые данные, чтобы можно было уже при создании проверить что все работает/теги считались верно и т д)

**Для первой версии**: пользователь сам вводит разметку ручками (да, придётся ее учить)
**Для нормальной версии**: должна быть штука, чтобы пользователь мог "накликивать" разметку (условно выбирать меню->добавить шаблонные данные->данные пациента->инициалы), после чего в файл будет подставляться нужный '<...>'. Плюс этой магии - если пользователь не знает/начинающий/не хочет учить разметочный язык - может просто накликать, а если ему быстрее ввести - вводит ручками.

### Редактирование шаблона
Редактирование возможно _только_ из списка шаблонов (но _не_ из формы услуги), так как шаблон меняется сразу для всех услуг, в которых он используется и если менять его из формы услуги, то может быть неочевиден этот момент.

Если решим разрешить редактирование из формы услуги - надо явно сказать пользователю что _или_ шаблон изменится во всех услугах (и дать их список), _или_ предложить клонировать шаблон, чтобы новая версия использовалась только в данной услуге

Вероятно, в форме шаблона (где мы его создаем/редактируем из списка шаблонов) стоит добавить список всех услуг, в которых он используется.

### Добавление/прикрепление шаблона к услуге
Предполагается что в форме услуги есть способ просмотреть доступные шаблоны и выбрать подходящие или создать новые шаблоны, в случае, если старые не подходят

Пока выглядит как-то так: (галочками отмечены выбранные для услуги шаблоны, без галочек - остальные, шаблоны с галочками должны быть выше всех остальных)
<img width="1108" alt="Снимок экрана 2022-06-04 в 14 52 04" src="https://user-images.githubusercontent.com/38105548/171997743-3bfaefb7-f2a9-4cdb-ab59-8ec5b74fa74a.png">

видео:
https://user-images.githubusercontent.com/38105548/171997554-6b090b4b-7f7c-4f09-9436-efe827477b78.mov

### Шаблоны и приёмы
#### Проведение приёма
Открываем вкладку приёма->начинаем проведение->
Файлы-шаблоны, прикрепленные к услуге, "копируются" в файлы-приёма, куда подставляются соответствующие значения 
То есть теперь в приёме хранятся копии-шаблонов, куда уже подставлены необходимые значения

Пользователь должен видеть и уметь редактировать файлы, полученные из шаблонов, и файлы, добавленные в приём дополнительно, желательно чтобы их можно было отличить в интерфейсе.

Сейчас это выглядит как-то так (но хочется чтобы было больше места для файлов, так как сейчас редактировать их зрительно довольно сложно, а это довольно большая часть работы):
<img width="1098" alt="Снимок экрана 2022-06-04 в 14 52 28" src="https://user-images.githubusercontent.com/38105548/171997757-47fa9442-6e10-46a0-a0f6-5356f9b56d1e.png">

видео:
https://user-images.githubusercontent.com/38105548/171997566-e31f204f-64ee-43dc-b08e-74e88c0de08b.mov

#### Прошедший проведённый приём
Отображаем файлы, полученные из шаблонов, и файлы, добавленные в приём дополнительно, желательно чтобы их можно было отличить.

#### Прошедший НЕпроведённый приём или запланированный приём
Отображаем шаблоны, куда подставлены значения + добавленные файлы, если есть.
НЕ делаем из шаблонов "файлы, полученные из шаблонов", так как если приём ещё не начался или пропущен(его могут перенести), то, к моменту проведения приёма, сами шаблоны/их набор для данной услуги могут изменится --> если бы мы просто при открытии таких приёмов сразу же прикрепляли бы (в базе) "файлы, полученные из шаблонов" к приёму, то были бы проблемы

**Comment by rust379** [comment]
Будет ли файл из шаблона онлайн редактироваться? т.е. вот в шаблоне есть поле <medicine.name>, мы в форме накликали нужные лекарства, в шаблоне эти данные появятся в момент накликивания или после завершения приема?
