### ISSUE TITLE
Обновление данных (создаем второго полезного менеджера)

### ISSUE THREAD

**Issue by strizh78** [rust379/MApp#200]
Когда в одном месте поменялись данные (например, ты из расписания перенес приём), то в табике самого приёма надо тоже обновить эту инфу

договаривались что будет менеджер, который будет ловить сигналы от условной базы и отправлять их во все "подписанные" формы, а формы (скорее всего внутри себя) будут уже сами решать затрагивает их это обновление или нет и фиксить данные соответственно

**Comment by strizh78** [comment]
https://medium.com/nuances-of-programming/паттерн-проектирования-наблюдатель-объект-под-прицелом-4dc3a453aaa4
https://ru.wikipedia.org/wiki/Издатель-подписчик_(шаблон_проектирования)
https://ru.wikipedia.org/wiki/Model-View-Controller

// вот тут неплохо обьясняются паттерны, там где-то в конце и mvc есть (она есть на русском, если что)
https://github.com/ajitpal/BookBank/blob/master/%5BO%60Reilly.%20Head%20First%5D%20-%20Head%20First%20Design%20Patterns%20-%20%5BFreeman%5D.pdf

**Comment by rust379** [comment]
Чтобы подписаться на событие БД, нужно вызвать метод `subscribe` у `Observer` и указать "Что" "На какой тип объекта" "На какое действие" надо подписаться.
После этого, по выбранному объекту и действию будет отправлен сигнал в слот с именем `{object}{Action}` (объект в lower сase и действие в title case)
`Observer::instance().subscribe(this, OBJECTS::APPOINTMENT, DB_ACTIONS::ADD);`
Для подписки на несколько действий, их можно перечислить в векторе
`Observer::instance().subscribe(this, OBJECTS::APPOINTMENT, {DB_ACTIONS::ADD, DB_ACTIONS::UPDATE});`
