### ISSUE TITLE
Шрифты надписей

### ISSUE THREAD

**Issue by rust379** [rust379/MApp#24]
Проработать шрифты надписей (шрифт + размер), для разных ОС

 - сделаем настройку в mainwindow, которая будет устанавливать размер всех шрифтов в системе  

 или

 - сделаем функцию, которая возьмет элемент (QLabel в данном случае) и цифру, на которую мы хотим увеличить дефолтный шрифт и изменит шрифт в нужную сторону и вызовем её в конструкторе для всех нужных элементов

_Originally posted by @strizh78 in https://github.com/rust379/MApp/issues/23#issuecomment-786711042_

**Comment by strizh78** [comment]
сделали через changeFont в interfaceUtils
