### ISSUE TITLE
Добавить редактор текста (мини)

### ISSUE THREAD

**Issue by rust379** [rust379/MApp#49]

**Comment by strizh78** [comment]
сейчас в приёме/других местах с редактированием файлика используется QTextEdit
Хотим сделать свой мини-редактор текста (возможно на основе того же QTextEdit) со скроллами и всякими полезными магическими штуками

**Comment by strizh78** [comment]
https://doc.qt.io/qt-5/qtwidgets-widgets-codeeditor-example.html

**Comment by strizh78** [comment]
Делать нечего было, решила погуглить как это делается

Оказалось что очень очень просто
У куте уже само реализовано почти все 
Есть какие то неочевидные места, но я пока забила на них

Во вторник покажу прототипчик

**Comment by strizh78** [comment]
<img width="909" alt="Снимок экрана 2021-08-21 в 22 53 33" src="https://user-images.githubusercontent.com/38105548/130333402-fe421e27-75bd-4fb1-b172-1e94ce6f0524.png">
