### ISSUE TITLE
MAppTable refactoring

### ISSUE THREAD

**Issue by rust379** [rust379/MApp#69]
Переработать код MAppTable
Цель: 
Сделать код более простым с возможностью удобного расширения функционала

**Comment by strizh78** [comment]
А какой хотя бы вектор расширения функционала мы рассматриваем?

Какой функционал сейчас
Какую часть мы хотим уметь расширять
Какой мы можем поступиться?

**Comment by rust379** [comment]
Добавление новых флагов, изменение поведения (например может понадобиться drag and drop для файлов),
пока новый функционал не рассматривается, но видно, что сейчас код не такой хороший, что его можно безболезненно модифицировать

**Comment by strizh78** [comment]
Первая часть мне нравится, давай сделаем

Вторая грустная очень
Как будто робот писал)
