### ISSUE TITLE
Dosages

### ISSUE THREAD

**Issue by rust379** [rust379/MApp#7]
Выделить дозировки в отдельный класс, 
чтоб поддерживал ввод как "От До Дозировка" так и в свободной форме

**Comment by strizh78** [comment]
обсудили, пока решили так:

выбираем сначала лекарство, когда оно выбрано показываем комбобокс ("от _ до_  дозировка") с существующими дозировками
(автоматом ставим наиболее подходящую по возрасту, но врач может выбрать другую)

если врачу не нравится, то рядом есть "карандашик"
если на него нажать, то вместо комбобокса ставим лайнедит "дозировка", где врач может ее изменить под конкретный случай

**Comment by strizh78** [comment]
надо предусмотреть, что возраста могут быть не указаны, или не указан один из них

**Comment by strizh78** [comment]
Тут ещё, возможно, стоит учесть пол пациента? Или не надо? Пофиг?
