### ISSUE TITLE
Проверить тайтлы форм на винде

### ISSUE THREAD

**Issue by strizh78** [rust379/MApp#88]
Для форм, которые прикрепляются к родительской, на маке нет тайтла
Надо проверить нет ли там какого-то косяак с неймингом на винде

особенно стоит обратить внимание на формы, которые "создать приём" у пациента и "повторить приём" в приёме
там из-за удаления openMode могло что-то косякнуться

**Comment by rust379** [comment]
Не нашел косячных форм, все хорошо.
Только вот главная - отображается как MainWindow

**Comment by strizh78** [comment]
Главную оставили такой потому что изначально это была форма "ну просто чтобы на кнопочки тыкать удобнее было"

Наверное пора ее переназвать)
А как? "Mapp"? Там же скоро будут вкладки и все страницы внутри этой будут

**Comment by rust379** [comment]
Да, MApp

**Comment by strizh78** [comment]
Завела ишью

Это можно закрыть, думаю
