### ISSUE TITLE
MappTable dimension_ деление на ноль

### ISSUE THREAD

**Issue by strizh78** [rust379/MApp#94]
<img width="1124" alt="Снимок экрана 2021-08-24 в 13 54 50" src="https://user-images.githubusercontent.com/38105548/130604685-d8290925-b14e-4445-9517-d7a851df68e3.png">

Как вопроизвести:
Открыть 2-3 приёма в расписании подряд
Видимо, попасть на какой-то приём без каких-то данных (тут не уверена)

Оно умрёт

**Comment by strizh78** [comment]
Возможно связано с пустотой таблицы файлов в приёме и рандомом?
потому что падает на разных приёмах, даже если кликать в одном порядке

https://user-images.githubusercontent.com/38105548/130605467-71f41cc2-31fb-4f55-9720-b9ff2dbb0a31.mov

**Comment by rust379** [comment]
Это довольно странно, ибо в начале ресайз евента стоит иф, в котором ретурнимся, при нулевом dimension_

**Comment by strizh78** [comment]
Видосик сделан на ветке равной мейну, то есть ничего нового я не добавила тут, из-за чего могло сломаться 

Сам видишь - отладка ссылается на эту строку и говорит про 0 в ней

**Comment by strizh78** [comment]
Может из-за порядка вызовов/сигналов/подобного что-то вызывается не так/не в том порядке? Dimension_ меняется в середине функции?

**Comment by rust379** [comment]
Нет, dimension_ может меняться только в функциях scale

**Comment by strizh78** [comment]
Посмотришь у себя, как время будет? Если воспроизведётся, то надо искать где косяк и почему

**Comment by strizh78** [comment]
Под дименшон меняется в середине функции имелось ввиду, что пока выполняем ресайз эвент, куте вызывает другую функцию, которая в этот момент меняет дименшон

Может такое быть?

**Comment by rust379** [comment]
Нет, это было бы очень странно, dimension - переменная формы, странно было бы, если ресайз евент его менял
