### ISSUE TITLE
Рефакторинг добавления форматов в файлы

### ISSUE THREAD

**Issue by strizh78** [rust379/MApp#96]
Ты хотел переписать что-то про расширения, чтобы было легко добавлять новые и сразу понимать в чем их открывать

Тип добавляешь jpeg и сразу говоришь что это такой же формат как png и jpg для нас 

И потом другим ревью добавить jpeg, чтобы проверить что форматы и правда не сложно добавлять

**Comment by strizh78** [comment]
где сейчас используется разрешение (полюшко extension у File):
> конструктор файла
> в форме файла (там пишется в значение это)
> в форме файла на основе типа extension решается какой табик показать
> в форме файла какая-то магия https://github.com/rust379/MApp/blob/138b028f683a2b3042dc5c33421bb4d47c2b1856/interface/file/fileForm.cpp#L100

**Comment by strizh78** [comment]
что хочется: иметь информацию и про реальное разрешение и про его "тип"

"тип" - условно делим по табикам/виджетам, то есть условные png, jpg, jpeg это один тип
txt - другой

**Comment by strizh78** [comment]
@rust379 
**смотри, что я вижу**

что нам надо обязательно знать само расширения (текстовый вид), для всяких сохранений картинок и подобного

при этом файлы, в зависимости от **типа** расширения делятся на категории
одна категория - один виджет для отображения


**что хочу сделать:**
в самом файле храним строковое расширение (тут ничего не меняется)

в форме файла появляется FileDisplayManager
FileDisplayManager знает про соответствия расширения категории. ему можно скормить файл и он создаст и выдаст готовый виджет для отображения

то есть
есть класс FileDisplayManager умеющий в getData setData и getDiplayWidget
в форме файла просто скармливаем ему файл с данными, получаем из него виджет и помещаем на форму

дальше:
все вьюверы файлов наследуются от общего класса FileViewer (interface)
у них должны быть метода setData, getData, getWidget

соответственно, у нас 2 наследника - для текстов и картинок
и FileDisplayManager отдает нам нужного наследника в зависимости от расширения и умеет передавать им данные


**плюсы, которые я вижу:**
 - легко добавить новое расширение - просто в FileDisplayManager указать к какому типу оно относится (сделать mapping["jpeg"] = FileViewType::IMAGE) ~~так добавим джипег~~
 - легко добавить новый тип: в FileDisplayManager говорим какие расширения он обрабатывает + пишем ему наследника FileViewer, который умеет получать данные из виджета и класть их туда  ~~так изи добавим пдф~~
 - легко сменить виджет (например сейчас заменить простой QTextEdit на текстовый редактор новый)
 - для каждого типа вывода на экран данных у нас в одном месте собрана вся обработка/получение/отдача данных (в наследнике FileViewer)
 - самой форме файла надо только скормить файл и данные в FileDisplayManager и сказать где на форме разместить виждет: мы уходим от нескольких мест, где нужно было анализировать в каком табе данные и т д, оно само происходит --> и при добавлении чего-то нового не получится так, что мы забыли какой-нибудь иф
 - мы, в отличии от табов, тупо не тратим время/память на существование остальных табов, которые не используются

**НО, возможно я глупая и всё переусложняю или не вижу недостатков очевидных
Посмотри пожалуйста и скажи согласен ли ты на такое)**

если так проще будет, то у меня есть набросок кода для этого
могу выкинуть на ревью просто чтобы ты идею глянул

**Comment by rust379** [comment]
Да, идея хорошая, давай делать
